### ISSUE TITLE
OP_RETURN bytes 80

### ISSUE THREAD

**Issue by datgrog** [assafshomer/protocolu#7]
[https://github.com/Colored-Coins/Colored-Coins-Protocol-Specification/wiki/Introduction#2-asset-metadata-and-the-rule-engine]

> Because of the 40 Bytes limit of the OP_RETURN field

Given that the limit was raised 80 bytes in version 0.10 (If I'm right), and the version node are approximatively at 78% more than 0.10 [https://bitnodes.21.co/dashboard/](url)
Colored coin use all available space ?

**Comment by oleiba** [comment]
@onepix, first of all thank you for the notice - the wiki is now updated to indicate 80 bytes, this is the [current max size used by the Colored-Coins protocol implementation](https://github.com/Colored-Coins/Transaction/commit/c6499b21cb5f5a1db6489716387d34a8c3512cf7).
80 bytes OP_RETURN is supported since [bitcoin-core's 0.11.0](https://bitcoin.org/en/release/v0.11.0).

Colored-Coins transactions exploit _up to_ 80 bytes, it depends on the data needed to be encoded.
Specifically, it depends on the varied amount of bytes needed to encode: transfer instructions, metadata torrent-hash and meta-data SHA2 (for transactions carrying meta-data), and the amount of asset units to issue (for issuance transactions).
Colored-Coins protocol implementation by Colu will _always_ use more than 40 bytes OP_RETURN for transactions _which carry meta-data_, because it pushes 20 bytes of torrent-hash plus 32 bytes of the meta-data SHA2.
The rest of Colored-Coins transactions _may_ use more than 40 bytes, but not necessarily.
The full coloring scheme can be found [here ](https://github.com/Colored-Coins/Colored-Coins-Protocol-Specification/wiki/Coloring-Scheme).
